// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oegvphxlgtgngmikytua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lZ3ZwaHhsZ3RnbmdtaWt5dHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjQ4OTIsImV4cCI6MjA2MjgwMDg5Mn0.CnjHZDJe2t3nCtQsw93_jYAaA4dJL68qJNWUntvQnUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);